apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: gcr.io/beaming-surfer-452610-r2/react:${{ github.sha }}


        ports:
        - containerPort: 80
