name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/873069651518/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider"
          service_account: "YOUR_SERVICE_ACCOUNT@beaming-surfer-452610-r2.iam.gserviceaccount.com"

      - name: Debug OIDC Token
        run: |
          echo "Fetching OIDC token..."
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL"
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.auth.outputs.id_token }}
          ACTIONS_ID_TOKEN_REQUEST_URL: "https://token.actions.githubusercontent.com"
