name: Build and Push to GCR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use Google Cloud
        run: gcloud auth configure-docker gcr.io

      - name: Set Environment Variables
        run: |
          PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          if [[ -z "$PROJECT_ID" || -z "$REPO_NAME" ]]; then
            echo "Error: PROJECT_ID or REPO_NAME is empty!"
            exit 1
          fi

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "GCR_REGISTRY=gcr.io/$PROJECT_ID" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$GCR_REGISTRY/$REPO_NAME:latest" >> $GITHUB_ENV
          echo "IMAGE_SHA=$GCR_REGISTRY/$REPO_NAME:${{ github.sha }}" >> $GITHUB_ENV

      - name: Ensure GCR Repository Exists
        run: |
          if ! gcloud artifacts repositories describe $REPO_NAME --location=us-central1 >/dev/null 2>&1; then
            gcloud artifacts repositories create $REPO_NAME --repository-format=docker --location=us-central1 --description="GCR Repository for $REPO_NAME"
          fi

      - name: Setup Java and Gradle
        if: env.BUILD_TOOL == 'gradle'
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR with Gradle
        if: env.BUILD_TOOL == 'gradle'
        run: |
          if [ -f "gradlew" ]; then chmod +x gradlew; fi
          ./gradlew build

      - name: Build and Push Docker Image to GCR
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_LATEST -t $IMAGE_SHA .
          echo "Pushing Docker image..."
          docker push $IMAGE_LATEST
          docker push $IMAGE_SHA

      - name: Verify Image in GCR
        run: gcloud container images list --filter="name:gcr.io/$PROJECT_ID/$REPO_NAME"
