name: Build and Push to GCR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use Google Cloud
        run: gcloud auth configure-docker gcr.io

      - name: Set Environment Variables
        run: |
          echo "PROJECT_ID=$(gcloud config get-value project)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Setup Java and Gradle
        if: env.BUILD_TOOL == 'gradle'
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR with Gradle
        if: env.BUILD_TOOL == 'gradle'
        run: |
          if [ -f "gradlew" ]; then chmod +x gradlew; fi
          ./gradlew build

      - name: Build and Push Docker Image to GCR
        run: |
          docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG

      - name: Verify Image in GCR
        run: gcloud container images list --filter="name:gcr.io/$PROJECT_ID/$REPO_NAME"
