name: Build and Deploy on GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/<PROJECT_ID>/locations/global/workloadIdentityPools/<POOL_ID>/providers/<PROVIDER_ID>'
          service_account: '<GCP_SA_EMAIL>'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker gcr.io

      - name: Set environment variables
        run: |
          echo "PROJECT_ID=<YOUR_GCP_PROJECT_ID>" >> $GITHUB_ENV
          echo "IMAGE_NAME=<YOUR_IMAGE_NAME>" >> $GITHUB_ENV
          echo "GKE_CLUSTER=<YOUR_GKE_CLUSTER>" >> $GITHUB_ENV
          echo "GKE_ZONE=<YOUR_GKE_ZONE>" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/<PROJECT_ID>/locations/global/workloadIdentityPools/<POOL_ID>/providers/<PROVIDER_ID>'
          service_account: '<GCP_SA_EMAIL>'

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/<DEPLOYMENT_NAME> <CONTAINER_NAME>=gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
          kubectl rollout status deployment/<DEPLOYMENT_NAME>
