name: Build and Deploy on GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  GKE_CLUSTER: my-gke-cluster
  GKE_ZONE: us-central1-a
  BUILD_TOOL: gradle  # Set this based on your project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Update gcloud components
        run: gcloud components update -q

      - name: Set Environment Variables
        run: |
          echo "PROJECT_ID=$(gcloud config get-value project)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Setup Java and Gradle
        if: env.BUILD_TOOL == 'gradle'
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR with Gradle
        if: env.BUILD_TOOL == 'gradle'
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Configure Docker to use Google Cloud
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update gcloud components
        run: gcloud components update -q

      - name: Set Environment Variables
        run: |
          echo "PROJECT_ID=$(gcloud config get-value project)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Get Kubernetes Credentials
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Deploy to GKE
        run: |
          kubectl create deployment $REPO_NAME --image=gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG --dry-run=client -o yaml | kubectl apply -f -
          kubectl set image deployment/$REPO_NAME $REPO_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG
          kubectl rollout status deployment/$REPO_NAME
