- name: Debug OIDC Token
  run: |
    echo "Fetching OIDC token..."
    curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
         "$ACTIONS_ID_TOKEN_REQUEST_URL"
  env:
    ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ACTIONS_ID_TOKEN_REQUEST_URL: ${{ steps.auth.outputs.id_token }}
