name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/873069651518/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider"
          service_account: "YOUR_SERVICE_ACCOUNT@beaming-surfer-452610-r2.iam.gserviceaccount.com"

      - name: Verify Authenticated Identity
        run: |
          gcloud auth list
